server:
  port: ${PORT:0}
  
spring:
  application:
    name: aggregator-ms
 
   
logging:
  level:
    org.springframework.web: debug
    com.app.aggregator.data.ProductsServiceClient : DEBUG
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    
feign:
  hystrix : 
    enabled : true
  
    

   

