server:
  port: ${PORT:0}
  
spring:
  application:
    name: products-ms
 
   
logging:
  level:
    org.springframework.web: debug
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    

   
