server:
  port: 8011
  
spring:
  application:
    name: gateway-microservice
    
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/
