server:
  port: 8011
  
spring:
  application:
    name: gateway-microservice
    
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/
      
authorization:
  token:
    header:
      name: Authorization
      prefix: Bearer

token:
  secret: secret
  
user:
  microservice:
    path:
      login: /users-ms/users/login
      signup: /users-ms/users
