spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/bharvi-bissa/microservice-central-config
          clone-on-start: true

server:
  port: 8012
  